[package]
name = "semantic_compression_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
prompt-compiler-storage = { path = "crates/prompt-compiler-storage" }
chrono = "0.4"
bincode = "1.3"
md5 = "0.7"
